### PR TITLE
Add ActiveMq target

### LINKED ISSUE #20: The same NLog binary on Windows and Linux
<p>We are building binaries on Windows only, but most of our console tools works fine on Linux under mono.</p>

<p>The only problem is NLog - if there is file target in config - everything (including logging) works fine until exit where all utilities hanging.</p>

<p>Utilities are merged into single .exe via ILMerge, so I cannot just replace NLog binary.</p>

<p>Is there a way to use NLog Windows binary on Linux?</p>

Moved from http://nlog.codeplex.com/workitem/6291

### LINKED ISSUE #495: ActiveMQ Integration
Is there a plan for a ActiveMQ target? 

There is an commit on https://github.com/jkowalski/NLog/pull/20 which could be the solution. Is an integration planned?

### PR DESCRIPTION
**Pull request by ghost**
Used pull request from NLog/NLog#20
closes NLog/NLog#20 and closes NLog/NLog#495

### CODE REVIEW

**Comment by Xharze** [comment]
Nuget package needs to be created before this is merged

**Comment by 304NotModified** [comment]
Is it not more convenient to merge this to a new branch?

**Comment by Xharze** [comment]
Yes it would have been, but I forgot about the NuGet package until I took a look at the pull request, that's the good part of pull requests you're forced to look at them again. I'll add the packing of this project later today or at latest tomorrow.

**Comment by Xharze** [comment]
This have been move to separate repository https://github.com/NLog/NLog.Contrib.ActiveMQ

**Pull request closed without merging**
